spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
server:
  port: 5000
