spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/demo'
    username: demo
    password: demo@345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
